- name: Garantir que Apache esta instalado
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Personalizar apache.conf
  copy:
    src: files/apache.conf
    dest: /etc/apache2/conf-available/zabbix.conf
    owner: root
    group: root
    mode: 0644
  notify: Reiniciar Apache

- name: Habilitar configuracao do Zabbix no Apache
  command: a2enconf zabbix
  args:
    creates: /etc/apache2/conf-enabled/zabbix.conf
  notify: Reiniciar Apache
